projects:
  edge0:
    schema:
      - schemas/edge0/composed.graphqls
    documents:
      - schemas/edge0/operations/*.graphql
  edge1:
    schema:
      - schemas/edge1/composed.graphqls
    documents:
      - schemas/edge1/operations/*.graphql
